WIP: add docExpansion and filter to swagger.display config
api-platform/core pull request #3731
Opened 2020-09-21 12:26 UTC by dvc

| Q             | A
| ------------- | ---
| Bug fix?      | no 
| New feature?  | yes 
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #3730
| License       | MIT
| Doc PR        | api-platform/docs#...

2020-09-22 09:41 UTC, dvc commented
Code quality breaks in other files: https://insight.symfony.com/projects/92d78899-946c-4282-89a3-ac92344f9a93/analyses/6895

Do i need to fix it? And how? :)

2020-09-29 14:14 UTC, soyuka commented
Nice work, as it's a new feature could you target the `master` branch please?

I'll add some comments. Don't worry about the symfony insight.

2020-09-29 14:18 UTC, soyuka commented on src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
> +                        ->arrayNode('display')
What do you think about using `ui` instead of `display`? 

```
swagger:
    ui:
        doc_expansion: 'full'
```

2020-09-29 14:18 UTC, soyuka commented on src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
> +        $container->setParameter('api_platform.swagger.doc_expansion', $config['swagger']['display']['doc_expansion']);
```suggestion
        $container->setParameter('api_platform.swagger_ui.doc_expansion', $config['swagger']['display']['doc_expansion']);
```

2020-09-29 14:18 UTC, soyuka commented on src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
> +        $container->setParameter('api_platform.swagger.filter', $config['swagger']['display']['filter']);
```suggestion
        $container->setParameter('api_platform.swagger_ui.filter', $config['swagger']['display']['filter']);
```

2020-09-30 09:28 UTC, dvc commented
@soyuka , thank you for review. I've fix it.

`ApiPlatform\Core\Bridge\Symfony\Bundle\Action\SwaggerUiAction` is deprecated in master.

2020-12-12 12:22 UTC, dvc commented
@soyuka , hello!

I've update this  PR. Can you review it?

2021-01-20 08:27 UTC, dunglas requested changes

2021-01-20 12:18 UTC, dvc commented on src/Bridge/Symfony/Bundle/Action/SwaggerUiAction.php
> +            'docExpansion' => $this->swaggerDocExpansion,
I'm not shure. 
There are some already used config values. Merging testing required. 
What about config validation? Is it user's responsibility? Should any options to be blacklisted for any reason?

2021-02-19 17:03 UTC, alanpoulain commented
Now uses a `ui_extra_configuration` key, like @dunglas asked.
Tested on the demo, with:
```yaml
    swagger:
        versions: [3, 2]
        api_keys:
            apiKey:
                name: Authorization
                type: header
        ui_extra_configuration:
            filter: true
            docExpansion: none
```
It shows:
![image](https://user-images.githubusercontent.com/10920253/108536413-bd588a00-72dc-11eb-9697-a8005ac618f3.png)

2021-02-23 09:34 UTC, merged

2021-02-23 09:34 UTC, alanpoulain commented
Thank you @dvc!