Add traversable paginator
api-platform/core pull request #3783
Opened 2020-10-23 21:59 UTC by toby-griffiths

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tickets       | n/a
| License       | MIT
| Doc PR        | api-platform/docs# (tbc)

I've had need of a paginator for my custom data provider that returns a Generator, so I thought I'd submit this as an addition to the core, if that's so desired?

* [x] Add tests and ensure they pass.
* [x] Never break backward compatibility.
* [x] Features and deprecations must be submitted against master branch.
* [ ] Update CHANGELOG.md file.

2020-10-24 13:31 UTC, toby-griffiths commented
Not sure what to do about the failed build checks.  The skipped tests that seems be be causing a failure are unrelated to my change, and now I'm seeing a `Cannot update only a partial set of packages without a lock file present.` error.  On other projects I could click to re-run the build checks, but I don't seem to have that option here.

2020-11-08 10:11 UTC, soyuka commented
we fixed our tests feel free to rebase to relaunch the CI

2020-11-08 10:16 UTC, soyuka approved these changes

2020-11-08 17:25 UTC, toby-griffiths commented
@soyuka I've rebased & the build is still failing on SwaggerUiAction for both phpcs & phpunit checks.  I can take a look at these in a fresh PR if you like?

There also looks to be a Github authentication issue?

2020-11-08 18:32 UTC, soyuka commented
Yes there's an issue with github authentification using composer 2 I haven't got the time to dig into that more :/

2020-11-08 18:34 UTC, soyuka approved these changes

2020-11-09 10:15 UTC, toby-griffiths commented
I know that feeling.  If I can find a little time I'll see if I can help out.

Would you be OK to add the `hacktoberfest-accepted` label in the meantime, as your approval doesn't seem to have registered on my Hacktober profile?

2020-11-14 20:29 UTC, toby-griffiths commented
Thank you @soyuka

2021-01-20 08:21 UTC, dunglas requested changes

2021-01-20 08:21 UTC, dunglas commented on src/DataProvider/TraversablePaginator.php
> +class TraversablePaginator implements \IteratorAggregate, PaginatorInterface
```suggestion
final class TraversablePaginator implements \IteratorAggregate, PaginatorInterface
```

2021-01-20 08:21 UTC, dunglas commented on CHANGELOG.md
> +* Add TraversablePaginator
Can you add it to a new `2.7.0` section please? We'll merge this new feature in the next version.

2021-01-20 08:21 UTC, dunglas commented on src/DataProvider/TraversablePaginator.php
> +            return 1;
```suggestion
            return 1.;
```

2021-01-20 08:21 UTC, dunglas commented on src/DataProvider/TraversablePaginator.php
> +    public function __construct(Traversable $iterator, float $currentPage, float $itemsPerPage, float $totalItems)
```suggestion
    public function __construct(\Traversable $iterator, float $currentPage, float $itemsPerPage, float $totalItems)
```

2021-01-20 08:21 UTC, dunglas commented on src/DataProvider/TraversablePaginator.php
> +use Traversable;
```suggestion
```

2021-02-17 17:51 UTC, merged

2021-02-17 17:51 UTC, alanpoulain commented
Thank you @toby-griffiths!