Subresource definition ADR proposal
api-platform/core pull request #3838
Opened 2020-11-19 10:20 UTC by soyuka

| Q             | A
| ------------- | ---
| Bug fix?      | na
| New feature?  | na
| BC breaks?    | no
| Deprecations? | na
| Tickets       |  #2706
| License       | MIT
| Doc PR        | na

@GregoireHebert @dunglas @vincentchalamon @Deuchnord

2020-11-19 11:02 UTC, vincentchalamon requested changes

2020-11-19 11:02 UTC, vincentchalamon commented on docs/adr/0000-subresources-definition.md
> + * @ApiResource()
> The `path` of these multiple `ApiResource` needs to be implicitly described.
```suggestion
 * @ApiResource(path="/companies")
```

2020-11-19 11:02 UTC, vincentchalamon commented on docs/adr/0000-subresources-definition.md
> + * @ApiResource(path="/companies/{companyId}/users")
Isn't it supposed to be on the User entity instead?

2020-11-19 12:14 UTC, vincentchalamon approved these changes

2020-11-19 13:04 UTC, Deuchnord commented on docs/adr/0000-subresources-definition.md
> +* Fix the actual `ApiSubresource` annotation
```suggestion
* Fix the current `ApiSubresource` annotation
```

2020-11-23 08:20 UTC, Deuchnord approved these changes

2020-11-24 23:37 UTC, dunglas approved these changes

2020-11-24 23:37 UTC, dunglas commented on docs/adr/0000-subresources-definition.md
> +# Subresource definition
```suggestion
# Subresource Definition
```

2020-11-26 09:07 UTC, merged