Add maker command to generate data providers/persisters
api-platform/core pull request #3850
Opened 2020-11-26 17:24 UTC by antograssiot

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #3849
| License       | MIT
| Doc PR        | no yet

I had this ready since a year probably for discussion

2020-11-26 17:40 UTC, soyuka commented
This is a really good start thanks! Maybe some improvements for later:
 - generate the support methods by asking what entity this data provider / persister targets
 - DataProvider: choose if you want to do collections, items or both (not sure if this is possible)

2020-11-26 18:01 UTC, antograssiot commented
I'll look into this soon

2020-11-26 21:10 UTC, dunglas requested changes
This looks great!

2020-11-26 21:10 UTC, dunglas commented on src/Bridge/Symfony/Maker/MakeDataPersister.php
> +class MakeDataPersister extends AbstractMaker
```suggestion
final class MakeDataPersister extends AbstractMaker
```

2020-11-26 21:10 UTC, dunglas commented on src/Bridge/Symfony/Maker/MakeDataPersister.php
> +            ->setDescription('Creates a new class to persists data')
```suggestion
            ->setDescription('Creates an API Platform data persister')
```

2020-11-26 21:10 UTC, dunglas commented on src/Bridge/Symfony/Maker/MakeDataPersister.php
> +            'Find the documentation at <fg=yellow>https://api-platform.com/docs/core/data-persisters/#data-persisters</>',
```suggestion
            'Find the documentation at <fg=yellow>https://api-platform.com/docs/core/data-persisters/</>',
```

2020-11-26 21:10 UTC, dunglas commented on src/Bridge/Symfony/Maker/MakeDataProvider.php
> +            ->setDescription('Creates a new class to provide data')
```suggestion
            ->setDescription('Creates an API Platform data povider')
```

2020-11-26 21:10 UTC, dunglas commented on src/Bridge/Symfony/Maker/MakeDataProvider.php
> +            'Find the documentation at <fg=yellow>https://api-platform.com/docs/core/data-providers/#data-providers</>',
```suggestion
            'Find the documentation at <fg=yellow>https://api-platform.com/docs/core/data-providers/</>',
```

2020-11-26 21:10 UTC, dunglas commented on src/Bridge/Symfony/Maker/Resources/skeleton/DataProvider.tpl.php
> +    public function getCollection(string $resourceClass, string $operationName = null, array $context = [])
```suggestion
    public function getCollection(string $resourceClass, string $operationName = null, array $context = []): iterable
```

2020-11-26 21:10 UTC, dunglas commented on src/Bridge/Symfony/Maker/Resources/skeleton/DataProvider.tpl.php
> +    public function getItem(string $resourceClass, $id, string $operationName = null, array $context = [])
```suggestion
    public function getItem(string $resourceClass, $id, string $operationName = null, array $context = []): object
```

Or maybe even the name of the entity?

2020-11-27 18:53 UTC, weaverryan commented
I love this idea!

What about asking a question related to decoration? I commonly want a data persister or data provider simply so that I can decorate the core persister/provider to add some functionality - this is mostly useful with entities. The question could be:

> Will this data persister be used for an entity class?

(if yes):

> Choose which entity:

A) Foo
B) Bar
C) Other entities...

And then... I think we wouldn't even need to ask them if they want to "decorate"/call the core persister... I would think that if you have an entity then you *always* would.

Or, another option would be to ask:

> Choose which API Resource class this data persister will be used for?

A) Foo
B) Bar
C) ... list all other API Resource classes
D) None/other (in case the user is doing something super custom)

Then, if the class is an entity, we decorate the core entity persister.

It definitely adds significant complexity... but it would also be very nice, so I wanted to at least mention the idea :).

Thanks!

2020-11-27 20:36 UTC, antograssiot commented
I've improved the initial proposal by including @soyuka and @dunglas proposals

You can now choose in data providers it you only want to generate item or collection data providers
I'va also added a new question regarding the target resource class with auto-completion

2020-12-01 17:18 UTC, dunglas requested changes

2020-12-01 17:18 UTC, dunglas commented on src/Bridge/Symfony/Maker/Resources/skeleton/DataPersister.tpl.php
> +   if (null !==$resource_class) {
```suggestion
   if (null !== $resource_class) {
```

2020-12-01 17:18 UTC, dunglas commented on src/Bridge/Symfony/Maker/Resources/skeleton/DataProvider.tpl.php
> +final class <?= $class_name ?> implements <?= ($generate_collection ? 'ContextAwareCollectionDataProviderInterface, ' : '') . ($generate_item ? 'ItemDataProviderInterface, ' : '')?>RestrictedDataProv
`implode()`?

2020-12-01 17:18 UTC, dunglas commented on src/Bridge/Symfony/Maker/Resources/skeleton/DataPersister.tpl.php
> +    public function remove($data, array $context = [])
maybe ```suggestion
    public function remove($data, array $context = []): void
```

2020-12-03 05:12 UTC, antograssiot commented
updated as requested, I've also improve code coverage and rebased @dunglas 
I like @weaverryan suggestion on the decoration but it might fit in a future PR, I'm not sure when I'll have time to work on this, probably not before Christmas holidays

2021-02-17 15:17 UTC, alanpoulain commented on src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
> +            ->end()
```suggestion
                ->arrayNode('maker')
                    ->{class_exists(MakerBundle::class) ? 'canBeDisabled' : 'canBeEnabled'}()
                ->end()
```

2021-02-17 15:35 UTC, alanpoulain commented on src/Bridge/Symfony/Maker/MakeDataPersister.php
> +
You should add the `getCommandDescription` static method instead of a call to `setDescription` (seems new to make it lazy).

2021-02-17 15:37 UTC, alanpoulain commented on src/Bridge/Symfony/Maker/MakeDataProvider.php
> +        $inputConfig->setArgumentAsNonInteractive('name');
Why not using the automatic prompt for the name?

2021-02-17 15:39 UTC, alanpoulain commented on src/Bridge/Symfony/Maker/Resources/help/MakeDataPersister.txt
> +The <info>%command.name%</info> command generates a new data persister class.
```suggestion
The <info>%command.name%</info> command generates an API Platform data persister class.
```

2021-02-17 15:39 UTC, alanpoulain commented on src/Bridge/Symfony/Maker/Resources/help/MakeDataProvider.txt
> +The <info>%command.name%</info> command generates a new data provider class.
```suggestion
The <info>%command.name%</info> command generates an API Platform data provider class.
```

2021-02-17 15:39 UTC, alanpoulain commented on src/Bridge/Symfony/Maker/Resources/skeleton/DataPersister.tpl.php
> +
No strict type?

2021-02-17 15:41 UTC, alanpoulain commented on src/Bridge/Symfony/Maker/Resources/skeleton/DataPersister.tpl.php
> +final class <?= $class_name ?> implements ContextAwareDataPersisterInterface
Shouldn't we add the `ResumableDataPersisterInterface` too by default?

2021-02-17 15:42 UTC, alanpoulain commented on tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
> +            'api_platform.mercure.listener.response.add_link_header',
```suggestion
```

2021-02-17 15:47 UTC, alanpoulain commented
I love it! :heart_eyes:
I think we can merge it as is and improve it later (for instance with @weaverryan's comment) later.
WDYT @antograssiot @api-platform/core-team?

2021-02-23 11:17 UTC, soyuka commented
@alanpoulain feel free to continue working on this branch as @antograssiot doesn't have much time to continue!

2021-06-18 12:50 UTC, merged

2021-06-18 12:51 UTC, alanpoulain commented
Thank you very much @antograssiot!