Throw an error when no identifier is defined
api-platform/core pull request #3871
Opened 2020-12-02 17:44 UTC by soyuka

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | kinda
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | api-platform/docs#...

2020-12-02 18:02 UTC, dunglas requested changes

2020-12-02 18:02 UTC, dunglas commented on src/Api/IdentifiersExtractor.php
> +            throw new RuntimeException(sprintf('No identifier found in "%s"', $resourceClass));
```suggestion
            throw new RuntimeException(sprintf('No identifier defined "%s". You should add #[\ApiPlatform\Core\Annotation\ApiProperty(identifier: true)]" on the property identifying the resource.', $resourceClass));
```

2020-12-02 19:08 UTC, merged

2021-01-24 20:16 UTC, maks-rafalko commented on src/Api/IdentifiersExtractor.php
> +            throw new RuntimeException(sprintf('No identifier defined "%s". You should add #[\ApiPlatform\Core\Annotation\ApiProperty(identifier: true)]" on the property identifying the resource."',
What do you think about 

```diff
- No identifier defined "%s".
+ No identifier defined in "%s".
```

I mean, "in" is missed from my point of view

2021-01-29 13:13 UTC, julienfalque commented
This new exception seems to break POST/PUT endpoints that use a DTO without id as the resource. Is that intended? If so, what are the alternatives?

2021-01-29 21:03 UTC, soyuka commented
It should not break unless your DTO is a resource. Please open an issue and provide a reproducer I definitely want to check this!

2021-01-31 14:02 UTC, maks-rafalko commented
@soyuka there is already an issue https://github.com/api-platform/core/issues/3975

Please re-read it, author has edited description