Fix for empty example and empty default value
api-platform/core pull request #3887
Opened 2020-12-05 12:45 UTC by Tayfun74

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #3882
| License       | MIT

2020-12-06 09:41 UTC, dunglas requested changes
Could you also add a test please?

2020-12-06 09:41 UTC, dunglas commented on src/JsonSchema/SchemaFactory.php
> -        if (!isset($propertySchema['default']) && null !== $default = $propertyMetadata->getDefault()) {
You can remove the test for `null` values, it's already handled by `empty`.

2020-12-06 13:24 UTC, dunglas approved these changes

2020-12-06 13:24 UTC, merged

2020-12-06 13:24 UTC, dunglas commented
Thank you @Tayfun74!

2020-12-10 08:04 UTC, drupol commented
@Tayfun74 I always try to never use `empty()` in my code because it's confusing.

I'm definitely sharing this point of view here: https://twitter.com/localheinz/status/1335638838279069696