Fix #4037 allow POST operations without identifiers
api-platform/core pull request #4052
Opened 2021-02-11 11:04 UTC by soyuka

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no (fxies bc)
| Tickets       | fixes #4037 #3975
| License       | MIT
| Doc PR        | TODO

This allows POST operations without itemOperations and without identifiers :)

2021-02-11 16:27 UTC, alanpoulain commented on features/main/overridden_operation.feature
> +  Scenario: Use a POST operation to do a Remote Procedure Call without identifiers
```suggestion
  Scenario: Use a POST operation to do a Remote Procedure Call without identifiers and with an output DTO
```

2021-02-13 07:45 UTC, dunglas requested changes

2021-02-13 07:45 UTC, dunglas commented on src/Bridge/Symfony/Routing/ApiLoader.php
> +        $operation['identifiers'] = !$resourceMetadata->getItemOperations() ? [] : (array) ($operation['identifiers'] ?? $resourceMetadata->getAttribute('identifiers', $this->identifiersExtractor ? $
Please don't nest ternary operators.

2021-02-13 07:45 UTC, dunglas commented on src/Swagger/Serializer/DocumentationNormalizer.php
> +                $resourceMetadata = $resourceMetadata->withAttributes(($resourceMetadata->getAttributes() ?: []) + ['identifiers' => !$resourceMetadata->getItemOperations() ? [] : $this->identifiersE
Same here

2021-02-15 10:03 UTC, merged