Feat/resource metadata collection
api-platform/core pull request #4351
Opened 2021-07-07 07:05 UTC by soyuka

2021-07-07 07:52 UTC, alanpoulain commented on src/Core/EventListener/WriteListener.php
> +            trigger_deprecation('api-platform/core', '2.7', sprintf('Use an implementation of "%s" instead of "%s".', DataPersisterInterface::class, ProcessorInterface::class));
The classes should be inverted.

2021-07-07 08:34 UTC, alanpoulain commented on tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
> -            ],
Should not be removed.

2021-07-07 08:39 UTC, soyuka commented on tests/Fixtures/TestBundle/Entity/JsonldContextDummy.php
> +     *             "@var"="@id",
revert

2021-07-07 08:39 UTC, soyuka commented on tests/Fixtures/app/AppKernel.php
> -            new MakerBundle(),
revert

2021-07-07 08:40 UTC, soyuka commented on tests/Hydra/JsonSchema/SchemaFactoryTest.php
> -    }
revert

2021-07-07 08:40 UTC, alanpoulain commented on tests/Bridge/Doctrine/EventListener/PublishMercureUpdatesListenerTest.php
> -        $iriConverterProphecy->getIriFromItem($toDeleteMercureOptions, UrlGeneratorInterface::NET_PATH)->willReturn('//example.com/dummy_offers/5')->shouldBeCalled();
Should not be removed.

2021-07-07 08:40 UTC, alanpoulain commented on tests/Bridge/Doctrine/EventListener/PublishMercureUpdatesListenerTest.php
> +        $resourceMetadataFactoryProphecy->create(DummyOffer::class)->willReturn(new ResourceMetadata(null, null, null, null, null, ['mercure' => ['topics' => 'http://example.com/custom_topics/1', 'da
Should not be removed.

2021-07-07 08:41 UTC, alanpoulain commented on tests/Bridge/Doctrine/EventListener/PublishMercureUpdatesListenerTest.php
> +        $this->assertSame(['http://example.com/dummies/1', 'http://example.com/dummies/2', 'http://example.com/custom_topics/1', '/dummies/1', '/users/3', 'http://example.com/dummies/3', 'http://exam
Should not be changed.

2021-07-07 08:42 UTC, alanpoulain commented on tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
> +        $propertyAccessor = self::$kernel->getContainer()->get('test.property_accessor');
`static` should be used.

2021-07-07 08:42 UTC, alanpoulain commented on tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
> +        $propertyAccessor = self::$kernel->getContainer()->get('test.property_accessor');
`static` should be used.

2021-07-07 08:46 UTC, alanpoulain commented on tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
> -            'api_platform.maker.command.data_provider',
Should not be removed.

2021-07-07 08:46 UTC, alanpoulain commented on tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
> -            'api_platform.argument_resolver.payload',
Should not be removed.

2021-07-07 13:07 UTC, alanpoulain commented on src/Metadata/Operation.php
> +     * @param bool            $serialize                      https://api-platform.com/docs/core/events/#the-event-system
Missing `$exceptionToStatus`?

2021-07-07 13:08 UTC, alanpoulain commented on src/Metadata/Resource/DeprecationMetadataTrait.php
> +            @trigger_error('The "path" option is deprecated in 2.7 and will be renamed to "uri_tempalte" in 3.0.', \E_USER_DEPRECATED);
```suggestion
            @trigger_error('The "path" option is deprecated in 2.7 and will be renamed to "uri_template" in 3.0.', \E_USER_DEPRECATED);
```

2021-07-07 13:24 UTC, alanpoulain commented on src/Metadata/Operation.php
> +     * @param int             $referenceType
Should probably be removed (prefer `urlGenerationStrategy` instead).

2021-07-10 18:34 UTC, Chris53897 commented
Hi. Can you please give us a little bit infos about this pr? 711 Files changed looks like a great step forward to Apip 3.0.

2021-07-20 16:03 UTC, soyuka commented
@Chris53897 it's an implementation of https://github.com/api-platform/core/blob/main/docs/adr/0002-resource-definition.md !

2021-07-23 13:55 UTC, vincentchalamon requested changes

2021-07-23 13:55 UTC, vincentchalamon commented on src/Core/OpenApi/Factory/OpenApiFactory.php
> +        foreach ($this->resourceNameCollectionFactory instanceof LegacyResourceNameCollectionFactoryInterface ? $this->resourceNameCollectionFactory->create(true) : $this->resourceNameCollectionFacto
Interface `LegacyResourceNameCollectionFactoryInterface` does not exist anywhere in the project. I guess you meant the legacy `ResourceNameCollectionFactoryInterface`, but I can't find it anywhere...

What did you mean here?

2021-07-23 13:55 UTC, vincentchalamon commented on src/Core/Bridge/Symfony/Messenger/DataTransformer.php
> +                $resourceMetadataCollection = $this->resourceMetadataFactory->create($context['resource_class'] ?? $this->getObjectClass($data));
`getObjectClass` requires an object, which is impossible according to line 56.

2021-07-23 13:55 UTC, vincentchalamon commented on src/Core/Bridge/Symfony/Bundle/ArgumentResolver/PayloadArgumentResolver.php
> +        dd($attributes);
Don't forget to remove this line, and uncomment or solve the following block

2021-08-03 21:05 UTC, soyuka commented
still needs some behat fixing, I've updated the description

2021-08-10 13:23 UTC, merged