Adding collectionKeyType JSON Schema
api-platform/core pull request #4385
Opened 2021-08-18 20:04 UTC by yoshz

| Q             | A
| ------------- | ---
| Branch?       | 2.6
| Tickets       | #4384
| License       | MIT
| Doc PR        | -

This fix makes sure collection key type is saved for collection properties.
Eg. this makes sure an associative array property has type 'object' instead of 'array'.

2021-08-18 22:35 UTC, dunglas requested changes
LGTM, but can you add a unit test please?

2021-08-19 13:53 UTC, dunglas approved these changes

2021-09-04 18:09 UTC, yoshz commented
Any update on this MR? Do you need a MR on master too?

2021-09-27 13:43 UTC, merged

2021-09-27 13:43 UTC, alanpoulain commented
Thanks!