Feat(doctrine): create new writeListener which only use processor
api-platform/core pull request #4426
Opened 2021-09-07 07:40 UTC by samuelbigard

| Q             | A
| ------------- | ---
| Branch?       | main 
| Type       |  Feature
| License       | MIT
| Doc PR        | api-platform/docs#...

2021-09-07 07:52 UTC, dunglas requested changes

2021-09-07 07:52 UTC, dunglas commented on src/Core/EventListener/WriteListener.php
> +        trigger_deprecation('api-platform/core', '2.7', sprintf('The listener %s is deprecated and will be removed in 3.0', __CLASS__));
You should also add a `@deprecated` annotation in the PHPDoc of the class.

2021-09-07 07:52 UTC, dunglas commented on src/Symfony/EventListener/WriteListener.php
> +            !$this->resourceMetadataFactory instanceof ResourceMetadataCollectionFactoryInterface &&
This type assertion always returns `true` isn't it?

2021-09-07 07:52 UTC, dunglas commented on src/Symfony/EventListener/WriteListener.php
> +        if ($this->processor instanceof ProcessorInterface && !$this->processor->supports($controllerResult, $attributes['identifiers'], $operation->getName(), $context)) {
Same here, `$this->processor instanceof ProcessorInterface` is always `true`.

2021-09-14 19:22 UTC, merged

2021-09-14 19:23 UTC, soyuka commented
Thanks @samuelbigard