chore: remove ApiPlatform\Core from src/
api-platform/core pull request #4841
Opened 2022-07-20 11:40 UTC by nawel-les-tilleuls

Removed ApiPlatform\Core from src/ and related occurences in tests/..

2022-07-20 14:51 UTC, vincentchalamon requested changes
Minor change, then LGTM :+1:
I'm just not 100% sure about the maker section deletion: was it deprecated in 2.7? Should we keep it in 3.0 to add (even empty) new commands on it? WDYT @soyuka?

2022-07-20 14:51 UTC, vincentchalamon commented on src/Api/FilterInterface.php
> +     * @see \Serializer\Filter\PropertyFilter::getDescription
```suggestion
     * @see \ApiPlatform\Serializer\Filter\PropertyFilter::getDescription
```

2022-07-20 15:17 UTC, vincentchalamon approved these changes
LGTM (waiting for confirmation about the maker section)

2022-07-20 17:20 UTC, dannyvw commented
See https://github.com/api-platform/core/pull/4827 for more changes. Also core namespace is removed.

2022-07-25 08:06 UTC, vincentchalamon commented
Closing as a Maker command is about to be added here: https://github.com/api-platform/core/pull/4423

2022-07-25 08:06 UTC, closed without merging