chore: add typehint to ProcessorInterface
api-platform/core pull request #4896
Opened 2022-08-16 08:37 UTC by alanpoulain

2022-08-22 07:09 UTC, vincentchalamon commented on src/State/ProcessorInterface.php
> +    public function process(object $data, Operation $operation, array $uriVariables = [], array $context = []): ?object;
Please also update phpdoc on 2.7 to be consistent

2022-08-22 07:10 UTC, vincentchalamon commented on src/Doctrine/Common/State/RemoveProcessor.php
> +        return null;
Why not returning the original object?

2022-08-22 07:49 UTC, vincentchalamon requested changes

2022-08-22 07:49 UTC, vincentchalamon commented on src/Symfony/Messenger/Processor.php
> +    private function persist(object $data, array $context = []): ?object
Please also update the `remove` method

2022-08-22 07:49 UTC, vincentchalamon commented on tests/Fixtures/TestBundle/State/OperationResourceProcessor.php
> +    private function persist(object $data, array $context = []): object
Please also update the `remove` method

2022-08-22 07:49 UTC, vincentchalamon commented on src/Symfony/Messenger/Processor.php
> +    public function process(object $data, Operation $operation, array $uriVariables = [], array $context = []): ?object
To be consistent with `src/Doctrine/Common/State/RemoveProcessor.php`, you should return null in case of DeleteOperationInterface.

2022-08-22 07:49 UTC, vincentchalamon commented on tests/Fixtures/TestBundle/State/OperationResourceProcessor.php
> +    public function process(object $data, Operation $operation, array $uriVariables = [], array $context = []): ?object
To be consistent with `src/Doctrine/Common/State/RemoveProcessor.php`, you should return null in case of DeleteOperationInterface.

2022-08-29 13:44 UTC, soyuka commented
I'm in favor of mixed as it's definitely possible on an RPC route to use arrays, integers, strings, null or any data type in a POST operation according to the HTTP specification. If we use objects only we may end up using objects representing scalar values (for example `NullContent` or `BinaryContent`). Not sure there's a real benefit in doing so.

2023-01-12 08:57 UTC, soyuka commented
we decided to keep mixed

2023-01-12 08:57 UTC, closed without merging