feat(Serializer): make MissingConstructorArgumentsException message consistent with Symfony's one and contain all missed args
api-platform/core pull request #5649
Opened 2023-07-04 13:56 UTC by ERuban

| Q             | A
| ------------- | ---
| Branch?       | main
| License       | MIT

Have found that if validation attributes are specified on DTOs or if the `Valid()` constraint is used on not api-resource property (just an entity in example) then Symfony's [AbstractNormalizer](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php) is used and it has a bit different `MissingConstructorArgumentsException` [exception message that also contains the list of missed arguments](https://github.com/symfony/symfony/blob/9b2ac59e8a373e983157f9a57de8ae951cc1a3ba/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L414).
But in ApiPlatform this exception has another [message and it contains only the first one of missed arguments in it](https://github.com/api-platform/core/blob/4ef0ef856ced658ac942fd6a2c6f7c5c563078d1/src/Serializer/AbstractItemNormalizer.php#L312).
This way someone, who relies on this message, in example, to convert it to something like validation error in the response, will get different messages.
So this PR fixes it.

Not sure that it is the BC break, but correct me if it is.

2023-07-05 22:01 UTC, soyuka commented
this looks good to me, thanks!

2023-07-08 07:45 UTC, soyuka commented
can you rebase? also edit your first message if you want to see the commitlint green :)

2023-07-08 10:52 UTC, ERuban commented
@soyuka done

2023-07-14 10:58 UTC, ERuban commented
@soyuka 👋

2023-07-20 12:44 UTC, dunglas requested changes
Nice one.

Exception messages aren't part of our BC promise, so it's ok.

2023-07-20 12:44 UTC, dunglas commented on src/Serializer/AbstractItemNormalizer.php
> +            if (\count($missingConstructorArguments) > 0) {
```suggestion
            if ($missingConstructorArguments) {
```

2023-07-21 06:29 UTC, dunglas commented
You have to update the tested message in the failing Behat test.

2023-07-21 09:20 UTC, ERuban commented
> You have to update the tested message in the failing Behat test.

oh, sorry, fixed

2023-07-31 12:56 UTC, ERuban commented
@dunglas @soyuka 👋

2023-08-01 08:27 UTC, soyuka commented
Tests should be green.

2023-08-25 15:07 UTC, ERuban commented
@soyuka @dunglas hey, have rebased and seems that ci became better. not sure that red checks are related to my changes. Could you check it please?

2023-10-17 17:10 UTC, ERuban commented
@soyuka  have rebased again... CI looks better

2023-10-17 18:10 UTC, soyuka commented
thanks, I need to check what branch to target but I think that this is from at least 3.1 I'll handle that!

2023-10-19 09:46 UTC, closed without merging