feat(serializer): support for getSupportedTypes (symfony 6.3)
api-platform/core pull request #5672
Opened 2023-07-15 13:50 UTC by mrossard

| Q             | A
| ------------- | ---
| Branch?       | 3.1
| Tickets       | https://github.com/api-platform/core/issues/5610

This is a quick draft for completing the work initiated here : https://github.com/api-platform/core/pull/5611 , which seems abandoned right now.

2023-07-15 16:56 UTC, john-dufrene-dev commented
@mrossard 

With this commit, all depreciations disappear ?

2023-07-15 17:45 UTC, mrossard commented
> @mrossard
> 
> With this commit, all depreciations disappear ?

it seems ok on my app, haven't tested everything yet.

2023-07-17 13:19 UTC, mrossard commented
Actually quite a lot of this is covered by existing tests, so i'll mark this as ready for review!

2023-07-20 09:01 UTC, dunglas requested changes
Thank you for working on this!

All `hasCacheableSupportsMethod()` must also be deprecated (as in Symfony).

2023-07-20 09:11 UTC, mrossard commented
> Thank you for working on this!
> 
> All `hasCacheableSupportsMethod()` must also be deprecated (as in Symfony).

Shouldn't they be kept until APIP stops supporting older versions of SF? Using them instead of just copying their return values might be a mistake on my part though - i thought it could serve as a reminder that they are still useful for older SF versions.

2023-07-20 09:13 UTC, mrossard commented on src/Elasticsearch/Serializer/ItemNormalizer.php
> +        return $this->decorated->getSupportedTypes($format);
Yes, missed this one, thanks.

2023-07-20 10:58 UTC, dunglas commented
> Shouldn't they be kept until APIP stops supporting older versions of SF?

It's what we'll do, but we should trigger a deprecation anyway to be able to remove these methods when we'll drop support for old Symfony versions, as they are also part of our public API. Old versions of Symfony will still work with newer versions of API Platform, but a deprecation will be triggered (as excepted, because these methods really are deprecated :D).

Also, to prevent PHPStan errors, you can use this trick: https://github.com/symfony/serializer/blob/f783a7ce6a048393f14f30e1094619f7729b1eb0/Debug/TraceableNormalizer.php#L44

2023-07-20 12:43 UTC, mrossard commented
> > Shouldn't they be kept until APIP stops supporting older versions of SF?
> 
> It's what we'll do, but we should trigger a deprecation anyway to be able to remove these methods when we'll drop support for old Symfony versions, as they are also part of our public API. Old versions of Symfony will still work with newer versions of API Platform, but a deprecation will be triggered (as excepted, because these methods really are deprecated :D).

ok, i'll add deprecations for this then (and replace the calls I added right away while I'm at it). Would version 3.2 be the correct target for these?

> Also, to prevent PHPStan errors, you can use this trick: https://github.com/symfony/serializer/blob/f783a7ce6a048393f14f30e1094619f7729b1eb0/Debug/TraceableNormalizer.php#L44

👍

2023-07-20 15:07 UTC, dunglas requested changes
Thanks for the changes, we're almost there!

To fix the remaining deprecation notices, you need to add the `@group legacy` annotation on tests testing the `hasCacheableSupportsMethod()` method (btw, it would be nice to add unit tests for `getSupportedTypes()`).

Normalizers from the TestBundle must also be upgraded to `getSupportedTypes()`.

2023-07-22 07:49 UTC, mrossard commented
This version should be better. I didn't add tests for getSupportedTypes() (yet?), but as they just return static arrays and are by design covered by functionnal tests I'm not sure how important those would be....?

2023-07-22 21:38 UTC, melroy89 commented
Thank you so much for this PR!

2023-07-24 12:29 UTC, merged

2023-07-24 12:29 UTC, dunglas commented
Thank you @mrossard and @Oipnet!