feat(doctrine): doctrine filters like laravel eloquent filters
api-platform/core pull request #6775
Opened 2024-11-05 09:59 UTC by vinceAmstoutz

| Q             | A
| ------------- | ---
| Branch?      | `main`
| Tickets        | Closes #6844 
| License       | MIT
| Doc PR        | _Coming soon_

**Completes #6749.**

Goal:

Using  Dotrine filters as we use Laravel Eloquent filters. Example using  a `BooleanFilter` with Symfony and Doctrine:
```php
#[ApiResource]
#[GetCollection(
    parameters: [
        'active' => new QueryParameter(
            filter: new BooleanFilter(),
        ),

        // support also for filter aliasing
        'enabled' => new QueryParameter(
            filter: new BooleanFilter(),
            property: 'active',
        ),
    ],
)]
#[ORM\Entity]
class FilteredBooleanParameter {
    // ...
}
```

TODO:
- [x] BooleanFilter
- [x] DateFilter
- [x] RangeFilter
- [x] Numeric
- [x] Exists
- [x] OrderFilter

**Will be done in another PR**:
- SearchFilter

2024-11-06 13:21 UTC, vinceAmstoutz commented
@soyuka As requested, the swagger UI doc looks like this for the `DateFilter`:
![image](https://github.com/user-attachments/assets/3239ad16-0aa8-44ce-ac6d-d27ed13d3588)

2024-11-07 15:13 UTC, vinceAmstoutz commented
@soyuka As requested, the swagger UI doc looks like this for the `RangeFilter`:

![image](https://github.com/user-attachments/assets/f1460081-b477-485b-afa6-89d3cb8c90a9)

2024-11-08 08:50 UTC, soyuka commented on src/Doctrine/Common/Filter/ManagerRegistryAwareInterface.php
> +    public function setManagerRegistry(?ManagerRegistry $managerRegistry): void;
```suggestion
    public function setManagerRegistry(ManagerRegistry $managerRegistry): void;
```

2024-11-08 08:50 UTC, soyuka commented on src/Doctrine/Odm/Extension/ParameterExtension.php
> +            if (null === ($v = $parameter->getValue()) || $v instanceof ParameterNotFound) {
```suggestion
            // TODO: remove the null equality as a parameter can have a null value
            if (null === ($v = $parameter->getValue()) || $v instanceof ParameterNotFound) {
```

2024-11-08 08:50 UTC, soyuka commented on src/Doctrine/Odm/Extension/ParameterExtension.php
> +                return;
```suggestion
                continue;
```

2024-11-08 08:50 UTC, soyuka commented on src/Doctrine/Odm/Filter/AbstractFilter.php
> +    public function setManagerRegistry(?ManagerRegistry $managerRegistry): void
```suggestion
    public function setManagerRegistry(ManagerRegistry $managerRegistry): void
```

2024-11-08 08:50 UTC, soyuka commented on src/Doctrine/Odm/Filter/BooleanFilter.php
> +        return $parameter->getSchema() ?? ['type' => 'boolean'];
```suggestion
        return ['type' => 'boolean'];
```

2024-11-08 08:50 UTC, soyuka commented on src/Doctrine/Orm/Filter/AbstractFilter.php
> +            throw new \RuntimeException('ManagerRegistry must be initialized before accessing it.');
```suggestion
            throw new RuntimeException('ManagerRegistry must be initialized before accessing it.');
```

use ApiPlatform\Metadata\RuntimeException

2024-11-08 08:50 UTC, soyuka commented on src/Doctrine/Odm/Filter/AbstractFilter.php
> +            throw new \RuntimeException('ManagerRegistry must be initialized before accessing it.');
```suggestion
            throw new RuntimeException('ManagerRegistry must be initialized before accessing it.');
```

2024-11-08 08:50 UTC, soyuka commented on src/Doctrine/Orm/Extension/ParameterExtension.php
> +use Psr\Container\ContainerExceptionInterface;
```suggestion
```

2024-11-08 08:50 UTC, soyuka commented on src/Doctrine/Orm/Extension/ParameterExtension.php
> +use Psr\Container\NotFoundExceptionInterface;
```suggestion
```

2024-11-08 08:50 UTC, soyuka commented on src/Doctrine/Orm/Extension/ParameterExtension.php
> +     * @throws NotFoundExceptionInterface
```suggestion
```

2024-11-08 08:50 UTC, soyuka commented on src/Doctrine/Orm/Filter/BooleanFilter.php
> +        return $parameter->getSchema() ?? ['type' => 'boolean'];
```suggestion
        return ['type' => 'boolean'];
```

2024-11-08 08:50 UTC, soyuka commented on src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
> +        private readonly LoggerInterface $logger,
as last argument + nullable, you can fix the laravel argument and put it last

2024-11-08 08:50 UTC, soyuka commented on src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
> +            } catch (\RuntimeException $exception) {
```suggestion
            } catch (RuntimeException $exception) {
```

Metadata\Exception

2024-11-08 08:50 UTC, soyuka commented on src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php
> +                $this->logger->alert($exception->getMessage(), ['exception' => $exception]);
```suggestion
                $this->logger?->alert($exception->getMessage(), ['exception' => $exception]);
```

2024-11-08 08:50 UTC, soyuka commented on src/Laravel/ApiPlatformProvider.php
> +                            $this->app->make(LoggerInterface::class),
move last

2024-11-08 08:50 UTC, soyuka commented on src/Metadata/Tests/Resource/Factory/ParameterResourceMetadataCollectionFactoryTests.php
> +        $logger = $this->createStub(LoggerInterface::class);
revert

2024-11-08 08:50 UTC, soyuka commented on src/Symfony/Bundle/Resources/config/metadata/resource.xml
> +            <argument type="service" id="logger" />
should be last + on-invalid=ignore

2024-11-08 08:50 UTC, soyuka commented on tests/Functional/Parameters/BooleanFilterTest.php
> +        yield 'active_true' => ['/filtered_boolean_parameters?active=true', 2];
```suggestion
        yield 'active_true' => ['/filtered_boolean_parameters?active=true', 2, 'true'];
```

2024-11-08 08:50 UTC, soyuka commented on tests/Functional/Parameters/BooleanFilterTest.php
> +        $expectedValue = str_contains($url, '=true') || str_contains($url, '=1');
instead, let's add a third arg inside the data provider

2024-11-14 15:03 UTC, soyuka commented on src/Doctrine/Orm/Filter/ExistsFilter.php
> +            $this->filterProperty($this->denormalizePropertyName($parameter->getProperty()), $value, $queryBuilder, $queryNameGenerator, $resourceClass, $operation, $context);
```suggestion
            $this->filterProperty($this->denormalizePropertyName($parameter->getProperty()), $value, $queryBuilder, $queryNameGenerator, $resourceClass, $operation, $context);
            return;
```

2024-11-14 15:03 UTC, soyuka commented on src/Doctrine/Orm/Filter/OrderFilter.php
> +        }
let's put this in a trait inside doctrine/common

PropertyPlaceholderOpenApiParameterTrait

2024-11-22 09:09 UTC, soyuka requested changes

2024-11-22 09:09 UTC, soyuka commented on src/Doctrine/Orm/Filter/OrderFilter.php
> +        }
We shouldn't need this as PropertyPlaceholderOpenApiParameterTrait alread declares a parameter per property. If this was for Validation we should move this to the ParameterValidationResourceMetadataCollectionFactory?

2024-11-22 09:09 UTC, soyuka commented on src/Symfony/Bundle/Resources/config/metadata/resource.xml
> +            <argument type="service" id="logger" on-invalid="null" />
```suggestion
            <argument type="service" id="logger" on-invalid="ignore" />
```

2024-11-22 09:09 UTC, soyuka commented on src/Doctrine/Orm/Filter/ExistsFilter.php
> +    public function getOpenApiParameters(Parameter $parameter): OpenApiParameter|array|null
we should use the trait here

2024-11-22 09:09 UTC, soyuka commented on src/Doctrine/Orm/Filter/DateFilter.php
>  }
note to self: we should probably log if a filter doesn't support the `:property` placeholder.

2024-12-10 12:46 UTC, merged

2024-12-28 13:01 UTC, 1ed commented
@vinceAmstoutz @soyuka I think, `composer.json` files should be updated to require the minimum version which contains the new symbols. For example for  `doctrine-orm` and `doctrine-odm` should be 

```
"api-platform/doctrine-common": "^4.1"
```

2024-12-28 14:44 UTC, vinceAmstoutz commented
> @vinceAmstoutz @soyuka I think, `composer.json` files should be updated to require the minimum version which contains the new symbols. For example for `doctrine-orm` and `doctrine-odm` should be
> 
> ```
> "api-platform/doctrine-common": "^4.1"
> ```

Why we should do that? @1ed

2024-12-28 15:24 UTC, 1ed commented
Because new symbols like `ManagerRegistryAwareInterface` were introduced in `api-platform/doctrine-common` and then used (in a way which is not backward compatible) in eg. `api-platform/doctrine-orm` which makes `api-platform/doctrine-orm: ^4.1` incompatible with all the versions of `api-platform/doctrine-common` before the interface was defined eg. <4.1 and IMHO this should be reflected in the package constrains, as the package is now broken with `api-platform/doctrine-common: <4.1`. And that stands for the other packages too.